### ISSUE TITLE
ValueError: When compiling the inner function of scan the following error has been encountered

### ISSUE THREAD

**Issue by loveJasmine** [hexahedria/biaxial-rnn-music-composition#18] opened 2016-10-31 03:27 UTC
this error occurs at 
 git remote -v
origin	https://github.com/bazarevsky/biaxial-rnn-music-composition (fetch)
origin	https://github.com/bazarevsky/biaxial-rnn-music-composition (push)

rzai@rzai00:~/prj/biaxial-rnn-music-composition$ CUDA_VISIBLE_DEVICES=1 python main.py 2>&1 | tee yknote---main.py---log
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
Loaded chpn-p14_format0
Loaded bk_xmas2_format0
Loaded grieg_waechter
Loaded scn15_7_format0

...................

Loaded mendel_op30_5_format0
Loaded chpn_op35_1
Loaded deb_prel
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    m = model.Model([300,300],[100,50], dropout=0.5)
  File "/home/rzai/prj/biaxial-rnn-music-composition/model.py", line 101, in __init__
    self.setup_predict()
  File "/home/rzai/prj/biaxial-rnn-music-composition/model.py", line 315, in setup_predict
    n_steps=self.steps_to_simulate )
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py", line 761, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "/home/rzai/prj/biaxial-rnn-music-composition/model.py", line 295, in step_time
    notes_result, updates = theano.scan(fn=self._predict_step_note, sequences=[time_final], outputs_info=note_outputs_info)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py", line 1058, in scan
    scan_outs = local_op(*scan_inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 539, in make_node
    inner_sitsot_out.type.dtype))
ValueError: When compiling the inner function of scan the following error has been encountered: The initial state (`outputs_info` in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 3) has dtype int16, while the result of the inner function (`fn`) has dtype int8. This can happen if the inner function of scan results in an upcast or downcast.
rzai@rzai00:~/prj/biaxial-rnn-music-composition$

**Comment by loveJasmine** [comment] 2016-10-31 06:10
also test in main branch by copy the directory music

rzai@rzai00:~/prj/biaxial-rnn-music-composition---main$ python main.py 
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
Loaded chpn-p14_format0
Loaded bk_xmas2_format0
Loaded grieg_waechter
Loaded scn15_7_format0
Loaded grieg_kobold
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    pcs = multi_training.loadPieces("music")
  File "/home/rzai/prj/biaxial-rnn-music-composition---main/multi_training.py", line 22, in loadPieces
    outMatrix = midiToNoteStateMatrix(os.path.join(dirpath, fname))
  File "/home/rzai/prj/biaxial-rnn-music-composition---main/midi_to_statematrix.py", line 8, in midiToNoteStateMatrix
    pattern = midi.read_midifile(midifile)
  File "/usr/local/lib/python2.7/dist-packages/midi/fileio.py", line 158, in read_midifile
    return reader.read(midifile)
  File "/usr/local/lib/python2.7/dist-packages/midi/fileio.py", line 9, in read
    pattern = self.parse_file_header(midifile)
  File "/usr/local/lib/python2.7/dist-packages/midi/fileio.py", line 18, in parse_file_header
    raise TypeError, "Bad header in MIDI file."
TypeError: Bad header in MIDI file.
rzai@rzai00:~/prj/biaxial-rnn-music-composition---main$ git remote -v
origin	https://github.com/hexahedria/biaxial-rnn-music-composition.git (fetch)
origin	https://github.com/hexahedria/biaxial-rnn-music-composition.git (push)
rzai@rzai00:~/prj/biaxial-rnn-music-composition---main$ vim main.py 
rzai@rzai00:~/prj/biaxial-rnn-music-composition---main$

**Comment by hexahedria** [comment] 2016-11-01 06:41
Closing as a duplicate of #16

(The second error you get seems to be unrelated, and indicates that one of your MIDI files is bad. Try removing that file from your dataset.)

**Closed by hexahedria** 2016-11-01 06:41 UTC
